# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-25 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picstagram', '0002_pictures_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='images',
            field=models.FileField(max_length=1000, upload_to=''),
        ),
    ]
