# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-26 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picstagram', '0003_auto_20170924_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='images',
            field=models.FileField(upload_to=''),
        ),
    ]
