# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-26 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picstagram', '0004_auto_20170925_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='caption',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
