# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-27 15:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('picstagram', '0006_auto_20170925_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='file_type',
        ),
        migrations.AddField(
            model_name='pictures',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 27, 15, 6, 43, 433513, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
