# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-27 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picstagram', '0007_auto_20170927_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
