# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-28 18:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picstagram', '0009_pictures_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='user',
        ),
    ]
