# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-28 19:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('picstagram', '0010_remove_pictures_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
